packages:
  - 'packages/*'
  - 'packages/integrations/*'
  - 'packages/plugins/*'
  - 'packages/themes/*'
  - 'apps/*'
allowBuilds:
  esbuild: true
  puppeteer: true
  sharp: true
  workerd: true
patchedDependencies:
  '@hono/vite-ssg@0.3.3': patches/@hono__vite-ssg@0.3.3.patch
