import fs from "node:fs";
import path from "node:path";
import { type ResolvedRiebeckiteConfig, uniqueStrings } from "@riebeckite/core";

export type GeneratedAssetPaths = {
  pluginStyles: string;
  themeStyles: string;
};

export function writeRiebeckiteAssetEntries(
  config: ResolvedRiebeckiteConfig,
  paths: GeneratedAssetPaths,
): void {
  writeGeneratedFile(paths.pluginStyles, createPluginStylesEntry(config));
  writeGeneratedFile(paths.themeStyles, createThemeStylesEntry(config));
}

function createPluginStylesEntry(config: ResolvedRiebeckiteConfig): string {
  return createStylesheetEntry(
    collectPluginStyleSpecifiers(config),
    "Plugin default styles, in resolved plugin order. Generated by @riebeckite/honox; do not edit. Import this before the theme stylesheet so a theme can override plugin defaults.",
  );
}

function createThemeStylesEntry(config: ResolvedRiebeckiteConfig): string {
  return createStylesheetEntry(
    config.theme.styles.map((style) => style.moduleSpecifier),
    "Theme styles. Generated by @riebeckite/honox; do not edit. Import this after the plugin stylesheet so the theme wins the plugin/theme cascade.",
  );
}

function collectPluginStyleSpecifiers(
  config: ResolvedRiebeckiteConfig,
): string[] {
  return config.plugins.flatMap((plugin) =>
    (plugin.assets ?? [])
      .filter((asset) => asset.kind === "style")
      .map((asset) => asset.moduleSpecifier),
  );
}

function createStylesheetEntry(
  moduleSpecifiers: string[],
  banner?: string,
): string {
  const imports = uniqueStrings(moduleSpecifiers)
    .map((specifier) => `@import ${JSON.stringify(specifier)};`)
    .join("\n");
  if (!banner) return imports;
  const header = `/* ${banner.replace(/\*\//g, "* /")} */`;
  return imports ? `${header}\n${imports}\n` : `${header}\n`;
}

function writeGeneratedFile(filePath: string, contents: string): void {
  if (readGeneratedFile(filePath) === contents) return;
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, contents);
}

function readGeneratedFile(filePath: string): string | undefined {
  try {
    return fs.readFileSync(filePath, "utf8");
  } catch (error) {
    if (isNotFoundError(error)) return undefined;
    throw error;
  }
}

function isNotFoundError(error: unknown): boolean {
  return (
    typeof error === "object" &&
    error !== null &&
    "code" in error &&
    error.code === "ENOENT"
  );
}
